chunks = [
    {
        "actions": [
            "AgentActionMessageLog(tool='answer_search', tool_input={'query': 'Justin Bieber recent controversies'}, log=\"\\nInvoking: `answer_search` with `{'query': 'Justin Bieber recent controversies'}`\\n\\n\\n\", message_log=[AIMessageChunk(content='', additional_kwargs={'function_call': {'arguments': '{\"query\":\"Justin Bieber recent controversies\"}', 'name': 'answer_search'}})])"
        ],
        "messages": [
            "AIMessageChunk(content='', additional_kwargs={'function_call': {'arguments': '{\"query\":\"Justin Bieber recent controversies\"}', 'name': 'answer_search'}})"
        ],
    },
    {
        "steps": [
            "AgentStep(action=AgentActionMessageLog(tool='answer_search', tool_input={'query': 'Justin Bieber recent controversies'}, log=\"\\nInvoking: `answer_search` with `{'query': 'Justin Bieber recent controversies'}`\\n\\n\\n\", message_log=[AIMessageChunk(content='', additional_kwargs={'function_call': {'arguments': '{\"query\":\"Justin Bieber recent controversies\"}', 'name': 'answer_search'}})]), observation=[Document(page_content='<strong>Justin</strong> <strong>Bieber</strong> is one of the biggest musicians in the world, but his career hasn’t been without <strong>controversy</strong>. When he was in his late teens and early twenties, the singer got into a variety of scandals. Many fans thought his career was over given all the bad press and legal troubles.But in <strong>recent</strong> ...', metadata={'title': \"Justin Bieber's 12 Biggest Scandals\", 'link': 'https://www.thethings.com/justin-bieber-biggest-scandals/'}), Document(page_content='One of Justin Bieber’s most controversial moments involved <strong>an attempt from actor Orlando Bloom to punch him in Ibiza</strong>. Justin’s bodyguards protected the singer, who had apparently escalated the conflict. After making a derogatory comment about Miranda Kerr, Orlando’s ex wife, Justin continued ...', metadata={'title': 'Justin Bieber’s Most Controversial Moments – BecomeGorgeous.com', 'link': 'https://www.becomegorgeous.com/entertainment/celebrity_gossip/justin-bieber-most-controversial-moments-A13780'}), Document(page_content='<strong>During a trip to Barcelona, the angry teen got into an altercation with a fan, leaving him bleeding after he sparked him in the face</strong>. The fan approached Justin while he was in the car and touched his face, and within a split second, the popstar retaliated with his fist.', metadata={'title': 'Justin Bieber – A List of Controversies & Crazy Moments', 'link': 'https://www.telltalesonline.com/34987/justin-bieber-controversies/'}), Document(page_content='Bieber was <strong>accused of allegedly punching a fan in Barcelona in November 2016.</strong> Video of the incident appeared to show the singer's hand making contact with the young man's face which was bloodied after the fan leaned into Bieber's vehicle.', metadata={'title': 'Justin Bieber’s troubled timeline | CNN', 'link': 'https://www.cnn.com/2013/03/28/showbiz/gallery/justin-bieber-2013/index.html'}), Document(page_content='<strong>Justin</strong> was 15 years old when he shot to fame, and resurfaced videos show him being groped, kissed, and asked about sex.', metadata={'title': \"Justin Bieber's Treatment As A Child Star Has Come Under Scrutiny\", 'link': 'https://www.buzzfeednews.com/article/stephaniesoteriou/justin-bieber-violated-child-star-disturbing'})])"
        ],
        "messages": [
            "FunctionMessage(content='[Document(page_content=\\'<strong>Justin</strong> <strong>Bieber</strong> is one of the biggest musicians in the world, but his career hasn’t been without <strong>controversy</strong>. When he was in his late teens and early twenties, the singer got into a variety of scandals. Many fans thought his career was over given all the bad press and legal troubles.But in <strong>recent</strong> ...\\', metadata={\\'title\\': \"Justin Bieber\\'s 12 Biggest Scandals\", \\'link\\': \\'https://www.thethings.com/justin-bieber-biggest-scandals/\\'}), Document(page_content=\\'One of Justin Bieber’s most controversial moments involved <strong>an attempt from actor Orlando Bloom to punch him in Ibiza</strong>. Justin’s bodyguards protected the singer, who had apparently escalated the conflict. After making a derogatory comment about Miranda Kerr, Orlando’s ex wife, Justin continued ...\\', metadata={\\'title\\': \\'Justin Bieber’s Most Controversial Moments – BecomeGorgeous.com\\', \\'link\\': \\'https://www.becomegorgeous.com/entertainment/celebrity_gossip/justin-bieber-most-controversial-moments-A13780\\'}), Document(page_content=\\'<strong>During a trip to Barcelona, the angry teen got into an altercation with a fan, leaving him bleeding after he sparked him in the face</strong>. The fan approached Justin while he was in the car and touched his face, and within a split second, the popstar retaliated with his fist.\\', metadata={\\'title\\': \\'Justin Bieber – A List of Controversies & Crazy Moments\\', \\'link\\': \\'https://www.telltalesonline.com/34987/justin-bieber-controversies/\\'}), Document(page_content=\\'Bieber was <strong>accused of allegedly punching a fan in Barcelona in November 2016.</strong> Video of the incident appeared to show the singer's hand making contact with the young man's face which was bloodied after the fan leaned into Bieber's vehicle.\\', metadata={\\'title\\': \\'Justin Bieber’s troubled timeline | CNN\\', \\'link\\': \\'https://www.cnn.com/2013/03/28/showbiz/gallery/justin-bieber-2013/index.html\\'}), Document(page_content=\\'<strong>Justin</strong> was 15 years old when he shot to fame, and resurfaced videos show him being groped, kissed, and asked about sex.\\', metadata={\\'title\\': \"Justin Bieber\\'s Treatment As A Child Star Has Come Under Scrutiny\", \\'link\\': \\'https://www.buzzfeednews.com/article/stephaniesoteriou/justin-bieber-violated-child-star-disturbing\\'})]', name='answer_search')"
        ],
    },
    {
        "output": "Justin Bieber has had his fair share of controversies over the years. Here are some of the recent controversies and scandalous moments involving Justin Bieber:\n\n1. **Scandals and Legal Troubles**: In his late teens and early twenties, Justin Bieber was involved in a variety of scandals and legal troubles, which led to a lot of bad press. However, despite these challenges, he has managed to continue his successful career.\n\n   [Read more](https://www.thethings.com/justin-bieber-biggest-scandals/)\n\n2. **Altercation with Orlando Bloom**: One of the most controversial moments involved an attempt from actor Orlando Bloom to punch Justin Bieber in Ibiza. The conflict escalated after Justin made a derogatory comment about Miranda Kerr, Orlando's ex-wife.\n\n   [Read more](https://www.becomegorgeous.com/entertainment/celebrity_gossip/justin-bieber-most-controversial-moments-A13780)\n\n3. **Altercation with a Fan in Barcelona**: During a trip to Barcelona, Justin got into an altercation with a fan, leaving the fan bleeding after he was struck in the face. The fan had approached Justin while he was in the car and touched his face, leading to the altercation.\n\n   [Read more](https://www.telltalesonline.com/34987/justin-bieber-controversies/)\n\n4. **Alleged Punching of a Fan in Barcelona**: In November 2016, Justin Bieber was accused of allegedly punching a fan in Barcelona. Video of the incident appeared to show the singer's hand making contact with the young man's face, which was bloodied after the fan leaned into Bieber's vehicle.\n\n   [Read more](https://www.cnn.com/2013/03/28/showbiz/gallery/justin-bieber-2013/index.html)\n\n5. **Treatment as a Child Star**: Justin Bieber's treatment as a child star has come under scrutiny, with resurfaced videos showing him being groped, kissed, and asked about sex when he was 15 years old.\n\n   [Read more](https://www.buzzfeednews.com/article/stephaniesoteriou/justin-bieber-violated-child-star-disturbing)\n\nThese are some of the recent controversies and scandalous moments involving Justin Bieber. If you'd like to delve deeper into any of these incidents, feel free to click on the provided links for more details.",
        "messages": [
            "AIMessage(content=\"Justin Bieber has had his fair share of controversies over the years. Here are some of the recent controversies and scandalous moments involving Justin Bieber:\\n\\n1. **Scandals and Legal Troubles**: In his late teens and early twenties, Justin Bieber was involved in a variety of scandals and legal troubles, which led to a lot of bad press. However, despite these challenges, he has managed to continue his successful career.\\n\\n   [Read more](https://www.thethings.com/justin-bieber-biggest-scandals/)\\n\\n2. **Altercation with Orlando Bloom**: One of the most controversial moments involved an attempt from actor Orlando Bloom to punch Justin Bieber in Ibiza. The conflict escalated after Justin made a derogatory comment about Miranda Kerr, Orlando's ex-wife.\\n\\n   [Read more](https://www.becomegorgeous.com/entertainment/celebrity_gossip/justin-bieber-most-controversial-moments-A13780)\\n\\n3. **Altercation with a Fan in Barcelona**: During a trip to Barcelona, Justin got into an altercation with a fan, leaving the fan bleeding after he was struck in the face. The fan had approached Justin while he was in the car and touched his face, leading to the altercation.\\n\\n   [Read more](https://www.telltalesonline.com/34987/justin-bieber-controversies/)\\n\\n4. **Alleged Punching of a Fan in Barcelona**: In November 2016, Justin Bieber was accused of allegedly punching a fan in Barcelona. Video of the incident appeared to show the singer's hand making contact with the young man's face, which was bloodied after the fan leaned into Bieber's vehicle.\\n\\n   [Read more](https://www.cnn.com/2013/03/28/showbiz/gallery/justin-bieber-2013/index.html)\\n\\n5. **Treatment as a Child Star**: Justin Bieber's treatment as a child star has come under scrutiny, with resurfaced videos showing him being groped, kissed, and asked about sex when he was 15 years old.\\n\\n   [Read more](https://www.buzzfeednews.com/article/stephaniesoteriou/justin-bieber-violated-child-star-disturbing)\\n\\nThese are some of the recent controversies and scandalous moments involving Justin Bieber. If you'd like to delve deeper into any of these incidents, feel free to click on the provided links for more details.\")"
        ],
    },
]

for chunk in chunks:
    if "actions" in chunk:
        print(f"Looking for {chunk['actions'][0].tool_input['query']}")
